version: '3'

services:
  cloudera:
      image: gethue/hue:local
      hostname: hue
      container_name: hue
      dns: 8.8.8.8
      ports:
      - "8888:8888"
      volumes:
        - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
        - ../../../desktop/libs/notebook/src/notebook/connectors:/usr/share/hue/desktop/libs/notebook/src/notebook/connectors
        - ../../../desktop/core/src/desktop/static/desktop/js/bundles/hue:/usr/share/hue/desktop/core/src/desktop/static/desktop/js/bundles/hue
      depends_on:
        database:
          condition: service_healthy
      restart: on-failure
  database:
      image: mysql:5.7
      ports:
          - "33061:3306"
      command: --init-file /data/application/init.sql
      volumes:
          - data:/var/lib/mysql
          - ./init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: hue
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
          interval: 5s
          timeout: 5s
          retries: 10
  starrocks:
      image: starrocks/allin1-ubuntu:latest
      container_name: starrocks
      ports:
      - "9030:9030"
      - "8030:8030"
      - "8040:8040"
      healthcheck:
          test: ["CMD", "mysql", "-h", "127.0.0.1", "-P", "9030", "-u", "root", "-e", "SHOW DATABASES"]
          interval: 10s
          timeout: 5s
          retries: 10
volumes:
  data:
